# https://github.com/cloudnative-pg/charts/tree/cb3d056272410532401d7317f236f01e67fe8d41/charts/cluster

cluster:
  instances: 1
  storage:
    size: 20Gi
    storageClass: local-path
  monitoring:
    enabled: false
  affinity:
    nodeSelector:
      node-role.kubernetes.io/master: "true"
