# https://github.com/cloudnative-pg/charts/tree/cb3d056272410532401d7317f236f01e67fe8d41/charts/cloudnative-pg

monitoring:
  podMonitorEnabled: false

nodeSelector:
  node-role.kubernetes.io/master: "true"
